#!/usr/bin/env python3
"""
HTTP Header Analyzer
=====================
Parses raw HTTP request and response text, identifies each header, and
prints a plain-language explanation of what the header does and why it
matters for performance, security, or caching.

Headers are grouped into categories:
  • General        — Connection, Date, Transfer-Encoding
  • Content        — Content-Type, Content-Length, Content-Encoding
  • Caching        — Cache-Control, ETag, Expires, Last-Modified
  • Security       — Strict-Transport-Security, Content-Security-Policy,
                     X-Frame-Options, X-Content-Type-Options, CORS headers
  • Authentication — Authorization, WWW-Authenticate, Cookie, Set-Cookie
  • Routing        — Host, Location, Forwarded, X-Forwarded-For

Concepts demonstrated:
  * Structure of HTTP/1.1 request and response messages
  * Role of each common header and its directives
  * Security hardening via response headers (HSTS, CSP, CORS)
  * Cache negotiation (ETag, If-None-Match, Cache-Control)

Usage:
    python http_header_analyzer.py                # analyze sample messages
    python http_header_analyzer.py --file req.txt # analyze from a file
"""

import argparse
import textwrap

HEADER_DOCS = {
    "host": ("Routing",
             "Specifies the target hostname and optional port. Required in "
             "HTTP/1.1 so a single server IP can host multiple domains."),
    "content-type": ("Content",
                     "Indicates the media type of the body "
                     "(e.g. text/html, application/json). The charset "
                     "parameter sets character encoding."),
    "content-length": ("Content",
                       "Decimal byte count of the body. Lets the receiver "
                       "know exactly when the message ends."),
    "content-encoding": ("Content",
                         "Compression applied to the body (gzip, br, deflate). "
                         "The client advertises support via Accept-Encoding."),
    "transfer-encoding": ("General",
                          "Hop-by-hop encoding, typically 'chunked', meaning "
                          "the body is sent in pieces with size prefixes."),
    "connection": ("General",
                   "Controls whether the TCP connection stays open after "
                   "the response. 'keep-alive' reuses the socket."),
    "date": ("General",
             "Timestamp when the message was generated by the origin server."),
    "cache-control": ("Caching",
                      "Directives for caching: max-age sets freshness lifetime; "
                      "no-store forbids caching; public/private controls where "
                      "caching is allowed."),
    "etag": ("Caching",
             "An opaque validator for a specific version of a resource. "
             "Clients send it back in If-None-Match for conditional requests."),
    "expires": ("Caching",
                "Legacy header giving an absolute expiry date. Superseded "
                "by Cache-Control max-age but still widely seen."),
    "last-modified": ("Caching",
                      "Timestamp of the last change. Clients can use "
                      "If-Modified-Since for conditional GETs."),
    "authorization": ("Auth",
                      "Carries credentials (Bearer token, Basic base64, etc.) "
                      "to authenticate the client to the server."),
    "www-authenticate": ("Auth",
                         "Server challenge sent with 401 responses. Tells the "
                         "client which authentication scheme to use."),
    "cookie": ("Auth",
               "Sends stored cookies back to the server. Each cookie is a "
               "name=value pair separated by semicolons."),
    "set-cookie": ("Auth",
                   "Server instructs the client to store a cookie. Attributes "
                   "include Path, Domain, Secure, HttpOnly, SameSite."),
    "strict-transport-security": ("Security",
        "HSTS — tells browsers to only connect over HTTPS for the specified "
        "max-age. 'includeSubDomains' extends to all subdomains."),
    "content-security-policy": ("Security",
        "CSP — restricts sources for scripts, styles, images, etc. to "
        "mitigate XSS and data injection attacks."),
    "x-frame-options": ("Security",
                        "Prevents the page from being embedded in iframes. "
                        "Values: DENY, SAMEORIGIN. Mitigates clickjacking."),
    "x-content-type-options": ("Security",
        "Set to 'nosniff' to stop browsers from MIME-type guessing, which "
        "can lead to script injection via misinterpreted files."),
    "access-control-allow-origin": ("Security",
        "CORS header specifying which origins may read the response. "
        "'*' allows any origin; a specific origin is more secure."),
    "access-control-allow-methods": ("Security",
        "CORS preflight header listing HTTP methods the server permits "
        "for cross-origin requests."),
    "location": ("Routing",
                 "Used with 3xx redirects to indicate the new URL. Also "
                 "appears in 201 Created responses to point to the new resource."),
    "x-forwarded-for": ("Routing",
                        "Comma-separated list of client IPs when the request "
                        "passes through proxies or load balancers."),
    "user-agent": ("General",
                   "Identifies the client software (browser, bot, CLI tool). "
                   "Servers may use it for content negotiation."),
    "accept": ("General",
               "Media types the client prefers, with optional quality weights "
               "(q=0.9). Drives server-side content negotiation."),
    "server": ("General",
               "Identifies the server software. Often obscured in production "
               "to reduce information leakage."),
}


def analyze_message(raw_text):
    """Parse and explain each header in a raw HTTP message."""
    lines = raw_text.strip().splitlines()
    if not lines:
        print("  (empty message)")
        return

    first_line = lines[0].strip()
    if first_line.startswith(("GET", "POST", "PUT", "DELETE",
                              "PATCH", "HEAD", "OPTIONS")):
        parts = first_line.split()
        print(f"\n  ► REQUEST LINE")
        print(f"    Method : {parts[0]}")
        print(f"    Path   : {parts[1] if len(parts) > 1 else '?'}")
        print(f"    Version: {parts[2] if len(parts) > 2 else '?'}")
    elif first_line.startswith("HTTP/"):
        parts = first_line.split(None, 2)
        print(f"\n  ► RESPONSE STATUS LINE")
        print(f"    Version: {parts[0]}")
        print(f"    Status : {parts[1] if len(parts) > 1 else '?'}")
        print(f"    Reason : {parts[2] if len(parts) > 2 else ''}")
    else:
        print(f"\n  ► First line: {first_line}")

    print(f"\n  {'Header':<32} {'Category':<10} Explanation")
    print(f"  {'-'*32} {'-'*10} {'-'*40}")

    for line in lines[1:]:
        line = line.strip()
        if not line or line.startswith(("{", "<", "[")):
            break
        if ":" not in line:
            continue
        name, _, value = line.partition(":")
        name = name.strip()
        value = value.strip()
        key = name.lower()
        cat, explanation = HEADER_DOCS.get(key, ("Other", "—"))
        short_val = (value[:35] + "…") if len(value) > 36 else value
        print(f"  {name + ': ' + short_val:<32} {cat:<10} ", end="")
        wrapped = textwrap.wrap(explanation, width=44)
        print(wrapped[0] if wrapped else "")
        for extra in wrapped[1:]:
            print(f"  {'':<32} {'':<10} {extra}")


SAMPLE_REQUEST = """\
GET /api/users?page=2 HTTP/1.1
Host: api.example.com
User-Agent: Mozilla/5.0
Accept: application/json
Authorization: Bearer eyJhbGciOi...
Cache-Control: no-cache
Cookie: session_id=abc123; theme=dark
X-Forwarded-For: 203.0.113.50
Connection: keep-alive
"""

SAMPLE_RESPONSE = """\
HTTP/1.1 200 OK
Date: Sat, 01 Jun 2025 12:00:00 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1024
Cache-Control: public, max-age=60
ETag: "a1b2c3d4"
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Access-Control-Allow-Origin: https://example.com
Access-Control-Allow-Methods: GET, POST, OPTIONS
Server: nginx/1.25.3
Connection: keep-alive
"""


def demo():
    print("╔══════════════════════════════════════════════════════════╗")
    print("║              HTTP Header Analyzer Demo                  ║")
    print("╚══════════════════════════════════════════════════════════╝")

    print("\n" + "=" * 60)
    print("  Sample HTTP Request")
    print("=" * 60)
    analyze_message(SAMPLE_REQUEST)

    print("\n" + "=" * 60)
    print("  Sample HTTP Response")
    print("=" * 60)
    analyze_message(SAMPLE_RESPONSE)

    print("\n" + "=" * 60)
    print("  Key take-aways:")
    print("  • Security headers (HSTS, CSP, X-Frame-Options) harden responses.")
    print("  • Cache-Control + ETag enable efficient conditional requests.")
    print("  • CORS headers gate cross-origin access to API data.")
    print("=" * 60 + "\n")


def main():
    parser = argparse.ArgumentParser(description="HTTP Header Analyzer")
    parser.add_argument("--file", type=str,
                        help="Path to a file containing raw HTTP text")
    args = parser.parse_args()

    if args.file:
        with open(args.file) as fh:
            analyze_message(fh.read())
    else:
        demo()


if __name__ == "__main__":
    main()
